export const verbTables = [
    {
        id: 0,
        form: "I",
        tense: "perfect",
        voice: "active",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "he did",
        exampleArabic: "فَعَلَ",
        conjugations: {
            "3sm": "فَعَلَ",
            "3sf": "فَعَلَتْ",
            "2sm": "فَعَلْتَ",
            "2sf": "فَعَلْتِ",
            "1s": "فَعَلْتُ",
            "3dm": "فَعَلَا",
            "3df": "فَعَلَتَا",
            "2d": "فَعَلْتُمَا",
            "3pm": "فَعَلُوا",
            "3pf": "فَعَلْنَ",
            "2pm": "فَعَلْتُمْ",
            "2pf": "فَعَلْتُمَا",
            "1p": "فَعَلْنَا",
        }
    },
    {
        id: 1,
        form: "I",
        tense: "imperfect-indicative",
        voice: "active",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "he does",
        exampleArabic: "يَفْعَلُ",
        conjugations: {
            "3sm": "يَفْعَلُ",
            "3sf": "تَفْعَلُ",
            "2sm": "تَفْعَلُ",
            "2sf": "تَفْعَلِينَ",
            "1s": "أَفْعَلُ",
            "3dm": "يَفْعَلَانِ",
            "3df": "تَفْعَلَانِ",
            "2d": "تَفْعَلَانِ",
            "3pm": "يَفْعَلُونَ",
            "3pf": "يَفْعَلْنَ",
            "2pm": "تَفْعَلُونَ",
            "2pf": "تَفْعَلْنَ",
            "1p": "نَفْعَلُ",
        }
    },
    {
        id: 2,
        form: "I",
        tense: "imperfect-subjunctive",
        voice: "active",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "[that] he does",
        exampleArabic: "يَفْعَلَ",
        conjugations: {
            "3sm": "يَفْعَلَ",
            "3sf": "تَفْعَلَ",
            "2sm": "تَفْعَلَ",
            "2sf": "تَفْعَلِي",
            "1s": "أَفْعَلَ",
            "3dm": "يَفْعَلَا",
            "3df": "تَفْعَلَا",
            "2d": "تَفْعَلَا",
            "3pm": "يَفْعَلُوا",
            "3pf": "يَفْعَلْنَ",
            "2pm": "تَفْعَلُوا",
            "2pf": "تَفْعَلْنَ",
            "1p": "نَفْعَلَ",
        }
    },
    {
        id: 3,
        form: "I",
        tense: "imperfect-jussive",
        voice: "active",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "he ought to do",
        exampleArabic: "يَفْعَلْ",
        conjugations: {
            "3sm": "يَفْعَلْ",
            "3sf": "تَفْعَلْ",
            "2sm": "تَفْعَلْ",
            "2sf": "تَفْعَلِي",
            "1s": "أَفْعَلْ",
            "3dm": "يَفْعَلَا",
            "3df": "تَفْعَلَا",
            "2d": "تَفْعَلَا",
            "3pm": "يَفْعَلُوا",
            "3pf": "يَفْعَلْنَ",
            "2pm": "تَفْعَلُوا",
            "2pf": "تَفْعَلْنَ",
            "1p": "نَفْعَلْ",
        }
    },
    {
        id: 4,
        form: "I",
        tense: "imperative",
        voice: "passive",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "Do!",
        exampleArabic: "اِفْعَلْ",
        conjugations: {
            "2sm": "اِفْعَلْ",
            "2sf": "اِفْعَلِي",
            "2d": "اِفْعَلَا",
            "2pm": "اِفْعَلُوا",
            "2pf": "اِفْعَلْنَ",
        }
    },
    {
        id: 5,
        form: "I",
        tense: "perfect",
        voice: "passive",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "It was done",
        exampleArabic: "فُعِلَ",
        conjugations: {
            "3sm": "فُعِلَ",
            "3sf": "فُعِلَتْ",
            "2sm": "فُعِلْتَ",
            "2sf": "فُعِلْتِ",
            "1s": "فُعِلْتُ",
            "3dm": "فُعِلَا",
            "3df": "فُعِلَتَا",
            "2d": "فُعِلْتُمَا",
            "3pm": "فُعِلُوا",
            "3pf": "فُعِلْنَ",
            "2pm": "فُعِلْتُمْ",
            "2pf": "فُعِلْتُمَا",
            "1p": "فُعِلْنَا",
        }
    },
    {
        id: 1,
        form: "I",
        tense: "imperfect-indicative",
        voice: "passive",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "It is being done",
        exampleArabic: "يُفْعَلُ",
        conjugations: {
            "3sm": "يُفْعَلُ",
            "3sf": "تُفْعَلُ",
            "2sm": "تُفْعَلُ",
            "2sf": "تُفْعَلِينَ",
            "1s": "أُفْعَلُ",
            "3dm": "يُفْعَلَانِ",
            "3df": "تُفْعَلَانِ",
            "2d": "تُفْعَلَانِ",
            "3pm": "يُفْعَلُونَ",
            "3pf": "يُفْعَلْنَ",
            "2pm": "تُفْعَلُونَ",
            "2pf": "تُفْعَلْنَ",
            "1p": "نُفْعَلُ",
        }
    },
    {
        id: 2,
        form: "I",
        tense: "imperfect-subjunctive",
        voice: "passive",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "It is being done",
        exampleArabic: "يُفْعَلَ",
        conjugations: {
            "3sm": "يُفْعَلَ",
            "3sf": "تُفْعَلَ",
            "2sm": "تُفْعَلَ",
            "2sf": "تُفْعَلِي",
            "1s": "أُفْعَلَ",
            "3dm": "يُفْعَلَا",
            "3df": "تُفْعَلَا",
            "2d": "تُفْعَلَا",
            "3pm": "يُفْعَلُوا",
            "3pf": "يُفْعَلْنَ",
            "2pm": "تُفْعَلُوا",
            "2pf": "تُفْعَلْنَ",
            "1p": "نُفْعَلَ",
        }
    },
    {
        id: 3,
        form: "I",
        tense: "imperfect-jussive",
        voice: "passive",
        infinitiveEnglish: "to do",
        infinitiveArabic: "فَعَلَ",
        exampleEnglish: "it is being done",
        exampleArabic: "يُفْعَلْ",
        conjugations: {
            "3sm": "يُفْعَلْ",
            "3sf": "تُفْعَلْ",
            "2sm": "تُفْعَلْ",
            "2sf": "تُفْعَلِي",
            "1s": "أُفْعَلْ",
            "3dm": "يُفْعَلَا",
            "3df": "تُفْعَلَا",
            "2d": "تُفْعَلَا",
            "3pm": "يُفْعَلُوا",
            "3pf": "يُفْعَلْنَ",
            "2pm": "تُفْعَلُوا",
            "2pf": "تُفْعَلْنَ",
            "1p": "نُفْعَلْ",
        }
    },
]